# Generated by Django 6.0.7 on 2026-07-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='mobileno',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
