# Generated by Django 6.0.7 on 2026-07-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0002_alter_storeuser_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='mobileno',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
