# Generated by Django 6.0.7 on 2026-07-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0003_alter_storeuser_mobileno'),
        ('stores', '0003_marketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuser',
            name='marketplaces',
            field=models.ManyToManyField(blank=True, related_name='employees', to='stores.marketplace'),
        ),
    ]
