# Generated by Django 6.0.7 on 2026-07-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0005_storeuser_groups_storeuser_is_active_and_more'),
        ('marketplaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='marketplaces',
            field=models.ManyToManyField(blank=True, related_name='employees', to='marketplaces.marketplace'),
        ),
    ]
