# Generated by Django 6.0.7 on 2026-07-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.CharField(blank=True, max_length=15, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=255)),
                ('store_address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
            ],
        ),
    ]
