# Generated by Django 6.0.7 on 2026-07-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
