# Generated by Django 6.0.7 on 2026-07-21 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0006_alter_storeuser_marketplaces'),
        ('stores', '0003_marketplace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marketplace',
        ),
    ]
