# Generated by Django 6.0.7 on 2026-07-27 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Store Assignment'), ('ASSIGNED', 'Assigned - Waiting for Employee'), ('VERIFIED', 'Item Found - Ready to Ship'), ('OUT_OF_STOCK', 'Item Missing/Out of Stock')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='stores.order'),
        ),
    ]
